#pragma once

#define TRACE_UART                      USART2
#define TRACE_UART_IRQHandler           USART2_IRQHandler
#define TRACE_DMA_IRQHandler            DMA1_Channel4_5_6_7_IRQHandler
#define TRACE_DMA_CLK_ENABLE()          __HAL_RCC_DMA1_CLK_ENABLE()
#define TRACE_UART_CLK_ENABLE()         __HAL_RCC_USART2_CLK_ENABLE()
#define TRACE_UART_TX_GPIO_CLK_ENABLE() __HAL_RCC_GPIOA_CLK_ENABLE()
#define TRACE_UART_TX_PIN               GPIO_PIN_2
#define TRACE_UART_TX_AF                GPIO_AF4_USART2
#define TRACE_UART_TX_GPIO_PORT         GPIOA
#define TRACE_UART_TX_DMA_CHANNEL       DMA1_Channel4
#define TRACE_UART_TX_DMA_REQUEST       DMA_REQUEST_4
#define TRACE_UART_DMA_TX_IRQn          DMA1_Channel4_5_6_7_IRQn
#define TRACE_UART_IRQn                 USART2_IRQn
#define TRACE_UART_FORCE_RESET()        __HAL_RCC_USART2_FORCE_RESET()
#define TRACE_UART_RELEASE_RESET()      __HAL_RCC_USART2_RELEASE_RESET()

#define SIGNAL_TIMER                     TIM2
#define SIGNAL_TIMER_CLK_ENABLE          __HAL_RCC_TIM2_CLK_ENABLE
#define SIGNAL_TIMER_CHANNEL_GPIO_PORT() __HAL_RCC_GPIOA_CLK_ENABLE();
#define SIGNAL_TIMER_CHANNEL_RED         TIM_CHANNEL_1
#define SIGNAL_GPIO_AF_CHANNEL_RED       GPIO_AF2_TIM2
#define SIGNAL_GPIO_PIN_RED              GPIO_PIN_0
#define SIGNAL_GPIO_CHANNEL_RED          GPIOA
#define SIGNAL_TIMER_CHANNEL_GREEN       TIM_CHANNEL_2
#define SIGNAL_GPIO_AF_CHANNEL_GREEN     GPIO_AF2_TIM2
#define SIGNAL_GPIO_PIN_GREEN            GPIO_PIN_1
#define SIGNAL_GPIO_CHANNEL_GREEN        GPIOA
#define SIGNAL_TIMER_CHANNEL_BLUE        TIM_CHANNEL_3
#define SIGNAL_GPIO_AF_CHANNEL_BLUE      GPIO_AF2_TIM2
#define SIGNAL_GPIO_PIN_BLUE             GPIO_PIN_2
#define SIGNAL_GPIO_CHANNEL_BLUE         GPIOA
